
#define CAN_ID_SERVER               0x000
#define CAN_ID_TIME                  0x00

#define CAN_ID_BATTERY              0x100
#define CAN_ID_COUNTED_AMP_SECONDS   0x00
#define CAN_ID_MA                    0x01
#define CAN_ID_OUTPUT_TARGET         0x02
#define CAN_ID_OUTPUT_STATE          0x03
#define CAN_ID_CHARGE_ENABLED        0x04
#define CAN_ID_DISCHARGE_ENABLED     0x05
#define CAN_ID_TEMPERATURE_8BFDP     0x06
#define CAN_ID_HEATER_TARGET         0x07
#define CAN_ID_HEATER_OUTPUT         0x08
#define CAN_ID_VOLTAGE               0x09
#define CAN_ID_AGING_AS_PER_HOUR     0x0A
#define CAN_ID_HEATER_PROPORTIONAL   0x0B
#define CAN_ID_HEATER_INTEGRAL       0x0C

#define CAN_ID_TANK                 0x200
#define CAN_ID_FRESH_TEMPERATURE     0x00
#define CAN_ID_FRESH_ROM             0x01
#define CAN_ID_FRESH_SUPPLY_MV       0x02
#define CAN_ID_FRESH_BASE_TEMP       0x03
#define CAN_ID_FRESH_BASE_MV         0x04
#define CAN_ID_FRESH_UV_PER_16TH     0x05
#define CAN_ID_FRESH_MV              0x06
#define CAN_ID_FRESH_DEPTH_MM        0x07
#define CAN_ID_FRESH_LITRES          0x08
#define CAN_ID_FRESH_SENSOR_FRONT    0x09
#define CAN_ID_FRESH_SENSOR_RIGHT    0x0A
#define CAN_ID_FRESH_TANK_WIDTH      0x0B
#define CAN_ID_FRESH_TANK_LENGTH     0x0C
#define CAN_ID_ACCELEROMETER_X_FLAT  0x0D
#define CAN_ID_ACCELEROMETER_Y_FLAT  0x0E
#define CAN_ID_ACCELEROMETER_Z_FLAT  0x0F
#define CAN_ID_ACCELEROMETER_X       0x10
#define CAN_ID_ACCELEROMETER_Y       0x11
#define CAN_ID_ACCELEROMETER_Z       0x12
#define CAN_ID_1_WIRE_ID_0           0x13
#define CAN_ID_1_WIRE_ID_1           0x14
#define CAN_ID_1_WIRE_ID_2           0x15
#define CAN_ID_1_WIRE_ID_3           0x16
#define CAN_ID_1_WIRE_DATA_0         0x17
#define CAN_ID_1_WIRE_DATA_1         0x18
#define CAN_ID_1_WIRE_DATA_2         0x19
#define CAN_ID_1_WIRE_DATA_3         0x1A
#define CAN_ID_LPG_MV                0x1B
#define CAN_ID_LPG_RESISTANCE        0x1C
#define CAN_ID_LPG_RESISTANCE_MIN    0x1D
#define CAN_ID_LPG_RESISTANCE_MAX    0x1E
#define CAN_ID_LPG_VOLUME_MIN        0x1F
#define CAN_ID_LPG_VOLUME_MAX        0x20
#define CAN_ID_LPG_VOLUME            0x21
#define CAN_ID_AMBIENT_OUTSIDE_ROM   0x22
#define CAN_ID_AMBIENT_HEATING_ROM   0x23
#define CAN_ID_AMBIENT_OUTSIDE_TEMP  0x24
#define CAN_ID_AMBIENT_HEATING_TEMP  0x25

#define CAN_ID_CONTROL              0x300
#define CAN_ID_PUMP                  0x00
#define CAN_ID_FILL                  0x01
#define CAN_ID_DRAIN                 0x02
#define CAN_ID_INVERTER              0x03
#define CAN_ID_D_PLUS                0x04
#define CAN_ID_EHU                   0x05
#define CAN_ID_PUMP_MIN_LITRES       0x06
#define CAN_ID_PUMP_DPLUS_LITRES     0x07
#define CAN_ID_DRAIN_MAX_LITRES      0x08
